// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_todo/test/todo_card_context_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_todo/data/todo.dart' as _i4;
import 'package:flutter_todo/data/todo_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Todo>> loadTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> loadOlderCompletedTodos() =>
      (super.noSuchMethod(
            Invocation.method(#loadOlderCompletedTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<int> addTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [todo]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> updateTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteCompletedTodos() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCompletedTodos, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> hasActiveTodosForCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveTodosForCategory, [categoryId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
